language: ruby

rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.3

gemfile:
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-5.1.x
  - gemfiles/Gemfile.rails-5.2.x
  - gemfiles/Gemfile.rails-6.0.x

matrix:
  exclude:
    # Travis by default installs bundler 2.1, rails 4.2 requires < 2.0
    - rvm: 2.5.3
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.6.3
      gemfile: gemfiles/Gemfile.rails-4.2.x
    # Rails 6.0.x doesn't support ruby prior to ruby 2.5.0
    - rvm: 2.4.5
      gemfile: gemfiles/Gemfile.rails-6.0.x
before_script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace

script:
  - bundle exec rspec spec
